### ISSUE TITLE
About 3D visualization of the surface distance

### ISSUE THREAD

**Issue by chengjianhong** [wulalago/FetalCPSeg#1]
@wulalago Hi, can you tell me how to plot the 3D visualization of the surface distance (in voxel) between segmented surface and ground truth?

**Comment by wulalago** [comment]
> @wulalago Hi, can you tell me how to plot the 3D visualization of the surface distance (in voxel) between segmented surface and ground truth?

@chengjianhong Please use the meshmetric3d to plot the 3D error map, outlined in https://www.nitrc.org/projects/meshmetric3d/

**Comment by chengjianhong** [comment]
@wulalago Thanks.
